AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  extractdefinitionsfromtex:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: extract.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          S3_BUCKET: arxiv-search-lambda-code
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::351532156193:role/lambda_everything'
